services:
  db:
    image: postgres:16.13-bookworm
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD:
  
 adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080